Devops
xGodMode/godmode-ganache-cli pull request #3
Opened 2021-02-13 15:46 UTC by benjamistan

Added buildspec.yml file to facilitate AWS CI/CD Pipeline.

2021-02-13 22:27 UTC, valmack commented on README.md
> +- This is a DevOps ephemeral branch for configuring the CI/CD in AWS. There are no new features or code.
Not sure I understand this... This pr is being merged into develop so this message isn't applicable. Anyway dont think we need different messages on different branches. And dont need diff branch for ci/cd.

2021-02-13 22:42 UTC, valmack requested changes
Great overall!

Besides the code questions a few clean up things:

- Make your commit messages more descriptive so that we actually know how each commit changes behavior of the pipeline

- If the commits feel like they should have the same message do an interactive rebase and just fold them into a single commit

- Since we do have the account id in commit history right now do an interactive rebase so that the account id gets removed from git history

This is a reference that I like for rebasing https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#squash-commits-together

2021-02-13 22:42 UTC, valmack commented on README.md
> +- Nothing to see here. To use GodMode-Ganache-CLI, the Develop branch is where you want to be
If needed let's just make this more clear like, `Use this library from `develop` branch`

2021-02-13 22:42 UTC, valmack commented on buildspec.yml
> +    AWS_ACCOUNT_ID: account_id
How does this work? Is it coming from github secrets? If not that's an easy way to get this.

2021-02-13 22:42 UTC, valmack commented on buildspec.yml
> +  files: imagedefinitions.json
Do we need an artifact? What is it used for?

2021-02-13 23:34 UTC, valmack commented on buildspec.yml
> +      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
Can we also include branch name as a tag?

2021-02-16 10:10 UTC, closed without merging

2021-02-16 10:11 UTC, benjamistan commented
Closing. This is a mess indeed. At this point it's more productive for me to try again from scratch than to unpick this chaos.